# https://github.com/pascalgn/automerge-action
name: PR Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
      WORKFLOW_CONCLUSION: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: ci result
        run: echo $WORKFLOW_CONCLUSION > ./ci-result.txt
      - uses: actions/upload-artifact@v3
        with:
          name: ci-result
          path: ./ci-result.txt

      - name: Set PR number
        run: echo $PULL_REQUEST_NUMBER > pr.txt
      - uses: actions/upload-artifact@v3
        with:
          name: pr-number
          path: ./pr.txt
