# https://github.com/pascalgn/automerge-action
name: PR Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest

    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number }}

    steps:
      # https://docs.github.com/en/graphql/reference/enums#checkconclusionstate
      - name: ci result
        run: echo $CHECK_SUITE_CONCLUSION > ./ci-result.txt
        env:
          CHECK_SUITE_CONCLUSION: ${{ github.event.check_suite.conclusion == 'success' }}
      - uses: actions/upload-artifact@v3
        with:
          name: ci-result
          path: ./ci-result.txt

      - name: Set PR number
        run: echo $PULL_REQUEST_NUMBER > pr.txt
      - uses: actions/upload-artifact@v3
        with:
          name: pr-number
          path: ./pr.txt
